name: 'Release'
description: 'Automate creating a release candidate branch'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch all branches
      run: git fetch --all

    - name: Checkout release
      run: |
        git checkout release
        git pull --ff-only origin release

    - name: Get commit hash from master
      id: commit
      run: echo "##[set-output name=hash;]$(git rev-parse --short master)"

    - name: Create release branch
      id: new_branch
      run: |
        new_branch=release-${{ steps.commit.outputs.hash }}
        git checkout -b $new_branch
        echo "##[set-output name=branch;]$new_branch"

    - name: Merge branch
      run: |
        git merge --ff-only origin/master
        git tag -a ${{ steps.commit.outputs.hash }} -m "${{ steps.commit.outputs.hash }}" || true
        git push origin ${{ steps.new_branch.outputs.branch }}

    - name: Output PR link
      run: |
      echo "Open Your Pull Request Here: https://github.com/${{ github.repository }}/compare/release...${{ steps.new_branch.outputs.branch }}"
